// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoodboardAI.Api.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MoodboardAI.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260723124958_UpdateSchemaForFeatureBranch")]
    partial class UpdateSchemaForFeatureBranch
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MoodboardAI.Api.Models.BlockedUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BlockedUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BlockerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BlockedUserId");

                    b.HasIndex("BlockerId", "BlockedUserId")
                        .IsUnique();

                    b.ToTable("BlockedUsers");
                });

            modelBuilder.Entity("MoodboardAI.Api.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Icon = "interior.png",
                            Name = "Interior Design"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Icon = "art.png",
                            Name = "Art & Illustration"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Icon = "tech.png",
                            Name = "Technology"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Icon = "food.png",
                            Name = "Food & Drink"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Icon = "travel.png",
                            Name = "Travel"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Icon = "nature.png",
                            Name = "Nature"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Icon = "photo.png",
                            Name = "Photography"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Icon = "arch.png",
                            Name = "Architecture"
                        });
                });

            modelBuilder.Entity("MoodboardAI.Api.Models.Interest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Interests");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111101"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "minimal",
                            Name = "Minimal"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111102"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "3d-art",
                            Name = "3D Art"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111103"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "app-mobile",
                            Name = "App Mobile"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111104"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "retro",
                            Name = "Retro"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111105"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "photography",
                            Name = "Photography"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111106"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "architecture",
                            Name = "Architecture"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111107"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "modern",
                            Name = "Modern"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111108"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "art",
                            Name = "Art"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111109"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "eco",
                            Name = "Eco"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111110"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "prints",
                            Name = "Prints"
                        });
                });

            modelBuilder.Entity("MoodboardAI.Api.Models.Pin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Title");

                    b.ToTable("Pins");

                    b.HasData(
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            AuthorId = new Guid("bbbbbbb1-bbbb-bbbb-bbbb-bbbbbbbbbbb1"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://i.pinimg.com/736x/1f/7e/53/1f7e53a190519f8ccbe427e431351e42.jpg",
                            Title = "Modern Living Room",
                            UpdatedAt = new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            AuthorId = new Guid("bbbbbbb2-bbbb-bbbb-bbbb-bbbbbbbbbbb2"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://i.pinimg.com/1200x/7c/f1/b3/7cf1b3f266e793502d1820b16f2df3b4.jpg",
                            Title = "Galaxy Art",
                            UpdatedAt = new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("MoodboardAI.Api.Models.PinTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PinId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.HasIndex("PinId", "TagId")
                        .IsUnique();

                    b.ToTable("PinTags");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ccccccc1-cccc-cccc-cccc-ccccccccccc1"),
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PinId = new Guid("99999999-9999-9999-9999-999999999999"),
                            TagId = new Guid("aaaaaaa2-aaaa-aaaa-aaaa-aaaaaaaaaaa2")
                        },
                        new
                        {
                            Id = new Guid("ccccccc2-cccc-cccc-cccc-ccccccccccc2"),
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PinId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            TagId = new Guid("aaaaaaa6-aaaa-aaaa-aaaa-aaaaaaaaaaa6")
                        });
                });

            modelBuilder.Entity("MoodboardAI.Api.Models.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaa1-aaaa-aaaa-aaaa-aaaaaaaaaaa1"),
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "minimal"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaa2-aaaa-aaaa-aaaa-aaaaaaaaaaa2"),
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "modern"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaa3-aaaa-aaaa-aaaa-aaaaaaaaaaa3"),
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "abstract"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaa4-aaaa-aaaa-aaaa-aaaaaaaaaaa4"),
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "botanical"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaa5-aaaa-aaaa-aaaa-aaaaaaaaaaa5"),
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "creative"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaa6-aaaa-aaaa-aaaa-aaaaaaaaaaa6"),
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "galaxy"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaa7-aaaa-aaaa-aaaa-aaaaaaaaaaa7"),
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "moon"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaa8-aaaa-aaaa-aaaa-aaaaaaaaaaa8"),
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "night-drive"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaa9-aaaa-aaaa-aaaa-aaaaaaaaaaa9"),
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "above-clouds"
                        });
                });

            modelBuilder.Entity("MoodboardAI.Api.Models.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Bio")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsOnboardingCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MoodboardAI.Api.Models.UserInterest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InterestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InterestId");

                    b.HasIndex("UserId", "InterestId")
                        .IsUnique();

                    b.ToTable("UserInterests");
                });

            modelBuilder.Entity("MoodboardAI.Api.Models.UserPrivacySettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("ContentVisibility")
                        .HasColumnType("boolean");

                    b.Property<bool>("PrivateAccount")
                        .HasColumnType("boolean");

                    b.Property<bool>("SearchVisibility")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserPrivacySettings");
                });

            modelBuilder.Entity("MoodboardAI.Api.Models.BlockedUser", b =>
                {
                    b.HasOne("MoodboardAI.Api.Models.UserEntity", "Blocked")
                        .WithMany()
                        .HasForeignKey("BlockedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MoodboardAI.Api.Models.UserEntity", "Blocker")
                        .WithMany()
                        .HasForeignKey("BlockerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blocked");

                    b.Navigation("Blocker");
                });

            modelBuilder.Entity("MoodboardAI.Api.Models.Pin", b =>
                {
                    b.HasOne("MoodboardAI.Api.Models.UserEntity", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoodboardAI.Api.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MoodboardAI.Api.Models.PinTag", b =>
                {
                    b.HasOne("MoodboardAI.Api.Models.Pin", "Pin")
                        .WithMany("PinTags")
                        .HasForeignKey("PinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoodboardAI.Api.Models.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pin");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("MoodboardAI.Api.Models.UserInterest", b =>
                {
                    b.HasOne("MoodboardAI.Api.Models.Interest", "Interest")
                        .WithMany()
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoodboardAI.Api.Models.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interest");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MoodboardAI.Api.Models.UserPrivacySettings", b =>
                {
                    b.HasOne("MoodboardAI.Api.Models.UserEntity", "User")
                        .WithOne()
                        .HasForeignKey("MoodboardAI.Api.Models.UserPrivacySettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MoodboardAI.Api.Models.Pin", b =>
                {
                    b.Navigation("PinTags");
                });
#pragma warning restore 612, 618
        }
    }
}
